Correcting the token name
autonomys/autonomys_gitbook pull request #12
Opened 2024-11-14 18:28 UTC by Xm0onh

Corrected the token name from 'ATC' to 'AI3' across all relevant files

2024-11-15 10:38 UTC, jim-counter requested changes
Made a few small suggestions.

2024-11-15 10:38 UTC, jim-counter commented on autonomys-solutions/autonomys-network/an-introduction-to-ai3-and-autocash.md
> +**Staking AI3s?**
```suggestion
**Staking AI3**
```

2024-11-15 10:38 UTC, jim-counter commented on autonomys-solutions/autonomys-network/an-introduction-to-ai3-and-autocash.md
> +Operators must lock up (stake) a certain minimum quantity of AI3s to gain the right to conduct transactions within the execution environments of Autonomys Network (called [domains](https://subnomicon
```suggestion
Operators must lock up (stake) a certain minimum quantity of AI3s to gain the right to conduct transactions within the execution environments of Autonomys Network (called [domains](https://subnomicon.subspace.network/docs/category/domains)). To increase the chance of executing and processing blocks, AI3 holders can nominate operators. The larger the pool, the higher the probability of producing a bundle and getting a reward for it. Operators are motivated to attract as many nominators as possible (up to a maximum of 256) to increase their staking pool.
```

2024-11-15 10:38 UTC, jim-counter commented on autonomys-solutions/autonomys-network/an-introduction-to-ai3-and-autocash.md
> +Operators are compensated for producing bundles with a nomination tax, a commission collected from the AI3 fees generated by executing and validating transactions. A portion of the commission is dist
```suggestion
Operators are compensated for producing bundles with a nomination tax, a commission collected from the AI3 fees generated by executing and validating transactions. A portion of the commission is distributed among the nominators who supported operators by adding AI3 to their staked pool.
```

2024-11-15 10:38 UTC, jim-counter commented on subspace-protocol/terminology.md
> +A Shannon is the smallest unit of an AI3, equal to $$10^{-18}$$AI3. AI3s are divisible up to 18 decimal places to allow for microtransactions.
```suggestion
A Shannon is the smallest unit of an AI3, equal to $$10^{-18}$$AI3. AI3 tokens are divisible up to 18 decimal places to allow for microtransactions.
```

2024-11-15 20:13 UTC, EmilFattakhov commented
Thanks very much, @Xm0onh, let me know if you have any problems acting on Jim's feedback. Appreciate your work!

2024-11-16 05:11 UTC, Xm0onh commented
Applied!

2024-11-18 10:01 UTC, jim-counter approved these changes
LGTM. Thanks!

2024-11-18 10:01 UTC, merged